<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EtapaProcesal;

class EtapasProcesalesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        // Lista completa y actualizada de etapas procesales para Colombia
        // Basada en la documentación oficial del sistema (167 etapas)
        $etapas = [
            // ETAPAS INICIALES Y PRESENTACIÓN
            'POR PRESENTAR',
            'DEMANDA PRESENTADA',
            'DEMANDA PRESENTADA 1',
            'DEMANDA PRESENTADA 2',
            
            // ADMISIÓN Y RECHAZO DE DEMANDAS
            'INADMITE',
            'INADMITE 2',
            'CUMPLE REQUISITOS',
            'CUMPLE REQUISITOS 2',
            'RECHAZADA INCUMPLIMIENTO REQUISITOS',
            'RECHAZADA POR COMPETENCIA',
            'RECHAZADA LUEGO DE CUMPLIR REQUISITOS',
            'ADMITE DEMANDA',
            'CALIFICACION DE DEMANDA',
            
            // AUTOS Y MANDAMIENTOS
            'AUTO ADMITE DEMANDA (PROCESO DE RESTITUCION)',
            'MANDAMIENTO DE PAGO',
            'MANDAMIENTO DE PAGO (PROCESO EJECUTIVO)',
            'NIEGA MANDAMIENTO DE PAGO',
            'CORRIGE MANDAMIENTO DE PAGO',
            'SOLICITUD DE CORRECCION DE AUTO QUE LIBRA MANDAMIENTO DE PAGO',
            
            // NOTIFICACIONES
            'PROCESO DE NOTIFICACION',
            'PENDIENTE DE NOTIFICACION',
            'REQUIERE PREVIO DESISTIMIENTO',
            'CLIENTE NOTIFICADO',
            'NOTIFICACION AL DEUDOR PARA ENTREGA DIRECTA',
            'NOTIFICACION A ACREEDORES',
            
            // AUDIENCIAS
            'AUDIENCIA DE TRAMITE',
            'AUDIENCIA RESOLUCION DE OBJECIONES',
            'AUDIENCIA DE GRADUACION Y CALIFICACION DE CREDITOS',
            'AUDIENCIA DE CONFIRMACION DE ACUERDO',
            'AUDIENCIA DE CONFIRMACION ACUERDO DE REORGANIZACION',
            'AUDIENCIA CONVALIDACION DE ACUERDO PRIVADO',
            'AUDIENCIA DE APROBACION DE ACUERDO DE NEGOCIACION DE DEUDAS',
            'AUDIENCIA RESOLUCION DE OBJECIONES NEGOCIACION',
            'AUDIENCIA RESOLUCION DE OBJECIONES LIQUIDACION PATRIMONIAL',
            'AUDIENCIA RESOLUCION DE OBJECIONES REORGANIZACION',
            'AUDIENCIA RESOLUCION DE OBJECIONES LIQUIDACION',
            'AUDIENCIA DE INCUMPLIMIENTO DEL ACUERDO DE REORGANIZACION',
            'AUDIENCIA DE NEGOCIACION DE DEUDAS',
            
            // DECISIONES JUDICIALES
            'AUTO INTERLOCUTORIO',
            'SENTENCIA',
            'AVOCA CONOCIMIENTO',
            'CONFIRMA PROVIDENCIA',
            'ORDENA CESAR LA EJECUCION',
            
            // LIQUIDACIONES
            'LIQUIDACION DE COSTAS',
            'LIQUIDACION DEL CREDITO',
            'TRASLADO DE LIQUIDACION',
            'APRUEBA LIQUIDACION',
            'ORDENAN LIQUIDACION PATRIMONIAL',
            'ADMITE LIQUIDACION PATRIMONIAL',
            'RECHAZA LIQUIDACION PATRIMONIAL',
            
            // SOLICITUDES DE TERMINACIÓN
            'SOLICITUD TERMINACION Y/O SUSPENSION',
            'SOLICITUD DE SUSPENSION DEL PROCESO',
            'SOLICITUD DE TERMINACION POR NOVACION',
            'SOLICITUD DE TERMINACION POR REESTRUCTURACION',
            'SOLICITUD TERMINACION PAGO DE LA MORA',
            'SOLICITUD RETIRO DE LA DEMANDA',
            'SOLICITUD DE TERMINACION PAGO DIRECTO',
            'SOLICITUD DE TERMINACION POR TRANSACCION',
            'SOLICITUD DE TERMINACION POR PAGO TOTAL',
            'SOLICITUD DE RETIRO PARA VOLVER A PRESENTAR',
            
            // ESTADOS DE SUSPENSIÓN
            'SUSPENDIDO',
            'SUSPENDIDO POR TRAMITE DE INSOLVENCIA',
            
            // TERMINACIONES DEL PROCESO
            'TERMINADO POR PAGO TOTAL',
            'TERMINADO POR RENUNCIA PODER',
            'TERMINADO POR PERENCION',
            'TERMINADO POR PAGO MORA',
            'TERMINADO POR PRESCRIPCION',
            'TERMINADO POR DESISTIMIENTO TACITO',
            'TERMINADO POR NOVACION',
            'TERMINADO POR TRANSACCION',
            'TERMINADO POR REESTRUCTURACION',
            'TERMINADO POR ADJUDICACION DE BIENES',
            'TERMINADO POR VENTA DE CARTERA',
            
            // RECURSOS
            'INTERPONE RECURSO',
            'TRASLADO RECURSO',
            'RESUELVE RECURSO',
            'ADMITE APELACION',
            'RECURSO CONTRA AUTO QUE LIBRA MANDAMIENTO DE PAGO',
            'RECURSO CONTRA AUTO QUE ADMITE DEMANDA (RESTITUCION)',
            'RECURSO CONTRA AUTO QUE TERMINA PROCESO POR DESISTIMIENTO TACITO (SIN SENTENCIA)',
            'RECURSO CONTRA AUTO QUE TERMINA PROCESO POR DESISTIMIENTO TACITO (CON SENTENCIA)',
            'RECURSO CONTRA AUTO QUE DICTA SENTENCIA',
            'RECURSO CONTRA AUTO QUE RECHAZA DEMANDA',
            'RECURSO CONTRA AUTO QUE NIEGA MANDAMIENTO DE PAGO',
            'RECURSO CONTRA AUTO QUE TERMINA PROCESO POR PAGO TOTAL',
            
            // RETIROS Y DEVOLUCIONES
            'RETIRADA POR PAGO TOTAL',
            'RETIRADA POR PAGO DE LA MORA',
            'RETIRADA PARA VOLVER A PRESENTAR',
            'RETIRADA PARA DEVOLVER DOCUMENTOS',
            'DEVOLUCION DE DOCUMENTOS A CLIENTE',
            'DEVOLUCION DE DOCUMENTOS AL CLIENTE - INCIAL',
            'DEVOLUCION DE DOCUMENTOS AL CLIENTE - INTERMEDIA',
            'DEVOLUCION DE DOCUMENTOS AL CLIENTE - FINAL',
            
            // RENUNCIA DE PODER
            'ABOGADO RENUNCIA PODER',
            
            // DOCUMENTOS
            'RECEPCION DE DOCUMENTOS',
            'RECEPCION DE DOCUMENTOS PARCIAL',
            'ELABORACION DE DEMANDA',
            'ASIGNACION SIN DOCUMENTOS',
            
            // PRUEBAS Y EXCEPCIONES
            'DECRETA PRUEBAS',
            'PROPONE EXCEPCIONES',
            'NO PROPONE EXCEPCIONES',
            'PRONUNCIAMIENTO DE EXCEPCIONES',
            'TRASLADO EXCEPCIONES',
            
            // PROYECTOS Y PRESENTACIONES
            'PRESENTA PROYECTO',
            'PRESENTA ACUERDO DE REORGANIZACION',
            'PRESENTA PROYECTO DE ADJUDICACION',
            'TRASLADO DE PROYECTO DE ADJUDICACION E INVENTARIO DE BIENES',
            'PRESENTACION DE ACREENCIAS',
            'PRESENTACION DE ACREENCIAS REORGANIZACION',
            'PRESENTACION DE ACREENCIAS LIQUIDACION',
            'PRESENTA ACUERDO',
            
            // OBJECIONES
            'OBJECIONES AL PROYECTO DE GRADUACION Y CALIFICACION',
            'OBJECIONES AL PROYECTO DE ADJUDICACION E INVENTARIO DE BIENES',
            'FORMULACION DE OBJECIONES A LA GRADUACION Y CALIFICACION DE CREDITOS',
            'FORMULACION DE OBJECIONES AL ACUERDO PRIVADO',
            'RESOLUCION DE OBJECIONES',
            'TRASLADO DE OBJECIONES',
            
            // ACUERDOS Y APROBACIONES
            'APRUEBA ACUERDO DE REORGANIZACION',
            'ACUERDO DE REORGANIZACION EN FIRME',
            'APRUEBA ACUERDO DE ADJUDICACION',
            'ACUERDO DE ADJUDICACION EN FIRME',
            'ACUERDO DE ADJUDICACION EN FIRME LIQUIDACION',
            'ACUERDO DE ADJUDICACION DE BIENES',
            'ACUERDO DE NEGOCIACION DE DEUDAS',
            'APRUEBA ACUERDO DE NEGOCIACION DE DEUDAS',
            'CONVALIDACION DE ACUERDO PRIVADO',
            'CONSTANCIA DE NO ACUERDO',
            'ACUERDO DE PAGO',
            'SIN DEMANDA POR ACUERDO DE PAGO',
            
            // TRASLADOS ESPECÍFICOS
            'TRASLADO PROYECTO DE CALIFICACION Y GRADUACION DE CREDITOS',
            'TRASLADO PROYECTO DE CALIFICACION Y GRADUACION DE CREDITOS REORGANIZACION',
            'TRASLADO PROYECTO DE CALIFICACION Y GRADUACION DE CREDITOS LIQUIDACION',
            
            // PROCESOS DE INSOLVENCIA
            'TRAMITE DE INSOLVENCIA',
            'ADMITE PROCESO DE INSOLVENCIA PERSONA NATURAL NO COMERCIANTE',
            'ADMITE PROCESO DE INSOLVENCIA PERSONA NATURAL COMERCIANTE',
            'ADMITE TRAMITE DE NEGOCIACION DE DEUDAS',
            'DECLARA INCUMPLIMIENTO AL ACUERDO DE NEGOCIACION DE DEUDAS',
            'TERMINA PROCESO DE REORGANIZACION EMPRESARIAL',
            'ADMITE PROCESO DE REORGANIZACION EMPRESARIAL',
            'DECRETA INCUMPLIMIENTO ACUERDO Y APERTURA A LIQUIDACION JUDICIAL',
            'DENUNCIA INCUMPLIMIENTO DE ACUERDO DE REORGANIZACION',
            'DEVUELVEN TRAMITE A CENTRO DE CONCILIACION',
            
            // GARANTÍAS MOBILIARIAS Y APREHENSIÓN
            'SOLICITUD DE APREHENSION',
            'SOLICITUD DE APREHENSION 2',
            'SOLICITUD DE APREHENSION AL JUEZ',
            'ORDEN DE APREHENSION',
            'ORDENAN APREHENSION DEL VEHICULO',
            'CAPTURA DE VEHICULO',
            'VEHICULO APREHENDIDO',
            'ENTREGA DEL BIEN',
            'ENTREGA VOLUNTARIA DEL VEHICULO',
            'AVALUO DEL BIEN',
            'AVALUO PERITO',
            'TRANSFERENCIA DE DOMINIO',
            'APROPIACION DEL VEHICULO',
            'APROPIACION DEL VEHICULO A NOMBRE DEL BANCO',
            'TERMINACION DE APREHENSION',
            'RETIRO DE SOLICITUD DE APRENHENSION',
            'RESTITUCION DEL BIEN',
            
            // CONTRATOS DE LEASING
            'DECLARA TERMINADO CONTRATO DE LEASING',
            'DECLARA TERMINADO CONTRATO DE LEASING Y ORDENA RESTITUCION',
            
            // DESISTIMIENTOS
            'DESISTIMIENTO DE LAS PRETENSIONES (PAGO DIRECTO)',
            'DESISTIMIENTO DE LAS PRETENSIONES',
            
            // REGISTROS Y NOTIFICACIONES ESPECIALES
            'INSCRIPCION COMFECAMARAS',
            'SOLICITUD INSCRIPCION DE EJECUCION CONFECAMARAS',
            'CARTA PREAVISO PAGO DIRECTO',
            'AVISO CARTA PRE INICIO EJECUCION AL CLIENTE',
            
            // CONDICIONES ESPECIALES
            'NO CUMPLE REQUISITOS',
            
            // INVESTIGACIÓN DE BIENES
            'INVESTIGACION DE BIENES',
            'INVESTIGACION DE BIENES POSITIVA',
            'INVESTIGACION DE BIENES NEGATIVA',
            
            // SUBSANACIÓN
            'SUBSANACION',
            
            // CESIÓN DE CRÉDITO
            'SOLICITUD CESION DE CREDITO',
            'ACEPTADA CESION DE CREDITO'
        ];

        // Limpiar tabla existente para evitar duplicados
        EtapaProcesal::query()->delete();
        
        // Eliminar duplicados del array manteniendo el orden
        $etapas = array_unique($etapas);
        
        $orden = 1;
        foreach ($etapas as $nombre) {
            EtapaProcesal::create([
                'nombre' => trim($nombre), // Limpiar espacios
                'orden'  => $orden++
            ]);
        }
        
        $this->command->info('Se han insertado ' . count($etapas) . ' etapas procesales correctamente.');
    }
}