<?php
// Server-side acceptance against an isolated SQLite file, with no external sends.
require dirname(__DIR__).'/vendor/autoload.php';
$app=require dirname(__DIR__).'/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
use App\Services\AbogadosBot\Policy;
use App\Services\AbogadosBot\Runtime;
$root=storage_path('app/private/abogados-bot/test-'.bin2hex(random_bytes(6)));mkdir($root,0700,true);
file_put_contents($root.'/runtime.json',json_encode(['owner'=>Policy::OWNER,'instance'=>'abogados','enabled'=>false,'activated_at'=>time()-120]));
file_put_contents($root.'/webhook-token','synthetic-test-secret');
$bot=new Runtime($root);$tests=[];
$check=function(string $name,bool $ok)use(&$tests){$tests[$name]=$ok;if(!$ok)throw new RuntimeException('TEST_FAILED_'.$name);};
$check('authentication_rejects_empty',!$bot->authenticated(''));
$check('authentication_rejects_wrong',!$bot->authenticated('wrong'));
$check('authentication_accepts_exact',$bot->authenticated('synthetic-test-secret'));
$check('unknown_lid_not_phone',Policy::jid(['remoteJid'=>'1234567890@lid'])===null);
$check('verified_lid_mapping',Policy::jid(['remoteJid'=>'231670619889791@lid'])===Policy::SANDRA);
$check('group_not_private',Policy::jid(['remoteJid'=>Policy::GROUP,'remoteJidAlt'=>Policy::SANDRA])===Policy::GROUP);
$check('mention_not_order',!Policy::directed('Dile a Jeison que mire eso'));
$check('direct_address',Policy::directed('Jeison, revisa mi solicitud'));
$check('yes_not_release',Policy::release('sí')===null);
$check('release_exact',Policy::release('Jeison, retoma este chat')===Policy::SANDRA);
$check('quotation_not_release',Policy::release('Ella dijo: Jeison, retoma este chat')===null);
$check('forward_not_authority',Policy::forwarded(['audioMessage'=>['contextInfo'=>['isForwarded'=>true]]])===true);
$g=Policy::plan('greeting','',true);$check('greeting_not_escalated',$g['ticket']===null&&str_contains($g['reply'],'Hola'));
$p=Policy::plan('appointment','',true,['date_time'=>true,'modality'=>true]);$check('appointment_not_premature',str_contains($p['reply'],'aún no está confirmada'));
$check('no_repeated_date',!str_contains(Policy::plan('appointment','',false,['date_time'=>true,'modality'=>false])['reply'],'día'));
$check('third_party_private',!preg_match('/Sandra|equipo|grupo/i',Policy::plan('third_party','',false)['reply']));
$fixture=function($id,$jid,$fromMe=false,$text='Hola') {return ['instance'=>'abogados','event'=>'messages.upsert','data'=>['key'=>['id'=>$id,'remoteJid'=>$jid,'fromMe'=>$fromMe],'messageTimestamp'=>time(),'messageType'=>'conversation','message'=>['conversation'=>$text]]];};
$phone='573000000001@s.whatsapp.net';$event=$fixture('SYNTHETIC0001',$phone);
$check('accept_incoming',!empty($bot->receive($event)['accepted']));
$check('deduplicate',!empty($bot->receive($event)['duplicate']));
$check('one_event_only',(int)$bot->query('SELECT COUNT(*) FROM events')->fetchColumn()===1);
$stored=$bot->query('SELECT body FROM events')->fetchColumn();$check('content_encrypted',!str_contains($stored,'Hola'));
$wrong=$event;$wrong['instance']='psicologos-en-colombia';try{$bot->receive($wrong);$ok=false;}catch(RuntimeException $x){$ok=$x->getMessage()==='INSTANCE_MISMATCH';}$check('other_company_rejected',$ok);
$old=$event;$old['data']['key']['id']='SYNTHETICOLD1';$old['data']['messageTimestamp']=time()-10000;$check('history_not_replayed',isset($bot->receive($old)['ignored']));
$check('groups_not_answered',isset($bot->receive($fixture('SYNTHETICGRP1',Policy::GROUP))['ignored']));
$bot->queue('first',$phone,'¡Hola! ¿En qué puedo ayudarte?');$bot->queue('first',$phone,'¡Hola! ¿En qué puedo ayudarte?');
$check('outbox_deduplicated',(int)$bot->query('SELECT COUNT(*) FROM outbox')->fetchColumn()===1);
$bot->receive($fixture('SYNTHETICHUM1',$phone,true,'Te atiendo personalmente.'));
$check('human_hold_immediate',(int)$bot->query('SELECT hold FROM chats WHERE jid=?',[$phone])->fetchColumn()===1);
$check('pending_reply_suppressed',$bot->query('SELECT state FROM outbox WHERE id=?',['first'])->fetchColumn()==='SUPPRESSED_HUMAN');
$bot->ticket(['id'=>'SYNTHETIC0001','chat'=>$phone],'Consulta jurídica: revisión profesional');$bot->ticket(['id'=>'SYNTHETIC0001','chat'=>$phone],'Consulta jurídica: revisión profesional');
$check('one_ticket',(int)$bot->query('SELECT COUNT(*) FROM tickets')->fetchColumn()===1);
$check('two_destinations',(int)$bot->query('SELECT COUNT(*) FROM outbox WHERE internal=1')->fetchColumn()===2);
$bot->query("UPDATE outbox SET mid='SYNTHETICSEND',state='ACCEPTED' WHERE id='first'");
$bot->receive(['instance'=>'abogados','event'=>'messages.update','data'=>['keyId'=>'SYNTHETICSEND','status'=>'DELIVERY_ACK']]);
$check('delivery_not_acceptance',$bot->query('SELECT state FROM outbox WHERE id=?',['first'])->fetchColumn()==='DELIVERED');
$check('disabled_no_send',!empty($bot->process()['disabled']));
$bot->flush();$check('disabled_flush_preserves_queue',(int)$bot->query("SELECT COUNT(*) FROM outbox WHERE state='READY'")->fetchColumn()===2);
$bot->query("UPDATE chats SET phase='review',last_reply='Previous response' WHERE jid=?",[$phone]);
$releaseEvent=$fixture('SYNTHETICREL1',Policy::SANDRA,false,'Jeison, retoma el chat 573000000001');$bot->receive($releaseEvent);
$releaseRow=$bot->query('SELECT * FROM events WHERE id=?',['SYNTHETICREL1'])->fetch();
$method=new ReflectionMethod(Runtime::class,'processEvent');$method->invoke($bot,$releaseRow);
$resumed=$bot->query('SELECT * FROM chats WHERE jid=?',[$phone])->fetch();
$check('release_restores_reception',!(bool)$resumed['hold'] && $resumed['phase']==='' && $resumed['last_reply']==='');
$check('fees_not_payment_claim',!str_contains(Policy::plan('fees','',false,['service'=>true])['reply'],'El pago'));
try{$bot->readProgramCase('123');$ok=false;}catch(RuntimeException $ex){$ok=$ex->getMessage()==='INVALID_RADICADO';}$check('program_rejects_invalid_identifier',$ok);
$bot->query('INSERT OR REPLACE INTO chats(jid,hold,baseline,phase,last_reply,updated) VALUES(?,0,1,?,?,?)',[Policy::SANDRA,'','',time()]);
$bot->receive($fixture('SYNTHETICCAP1',Policy::SANDRA,false,'Que puedes hacer'));
$method->invoke($bot,$bot->query('SELECT * FROM events WHERE id=?',['SYNTHETICCAP1'])->fetch());
$check('capability_followup_in_explicit_context',$bot->query('SELECT reason FROM events WHERE id=?',['SYNTHETICCAP1'])->fetchColumn()==='CAPABILITIES_REPLY');
$bot->query('UPDATE chats SET hold=1 WHERE jid=?',[Policy::SANDRA]);
$bot->receive($fixture('SYNTHETICCAP2',Policy::SANDRA,false,'Jeison que puedes hacer'));
$method->invoke($bot,$bot->query('SELECT * FROM events WHERE id=?',['SYNTHETICCAP2'])->fetch());
$check('capability_followup_never_lifts_hold',$bot->query('SELECT state FROM events WHERE id=?',['SYNTHETICCAP2'])->fetchColumn()==='OBSERVED_HUMAN');
$check('safe_followup_cases',Policy::capability('Puedes revisar procesos por mí?')==='cases');
$check('safe_followup_judiciary',Policy::capability('Y puedes revisar la rama judicial?')==='judiciary');
$check('safe_followup_changes',Policy::capability('Y hacer cambios en el programa?')==='changes');
$check('safe_followup_help',Policy::capability('Con que puedes ayudarme')==='general');
$check('capability_is_not_mutation_authority',Policy::capability('Jeison cambia el estado de este proceso')===null);
$check('third_person_is_not_capability',Policy::capability('Dile a Jeison que revise procesos')===null);
$check('name_alone_directed',Policy::directed('Jeison'));
$alert=Illuminate\Support\Facades\Crypt::decryptString($bot->query('SELECT body FROM outbox WHERE internal=1 LIMIT 1')->fetchColumn());
$check('internal_alert_clear_without_code',!str_contains($alert,'Solicitud AB-')&&!str_contains($alert,'Requiere atención. Detalle privado'));
echo json_encode(['passed'=>count($tests),'failed'=>0,'tests'=>$tests,'externalMessages'=>0,'businessWrites'=>0],JSON_UNESCAPED_UNICODE).PHP_EOL;
