<?php
require '/code/vendor/autoload.php';
$app=require '/code/bootstrap/app.php';$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
use App\Services\AbogadosBot\{Policy,Runtime,ChiefLearning};
use Illuminate\Support\Facades\Crypt;
$root=storage_path('app/private/abogados-bot/test-learning-'.bin2hex(random_bytes(6)));mkdir($root,0700,true);
file_put_contents($root.'/runtime.json',json_encode(['owner'=>Policy::OWNER,'instance'=>'abogados','enabled'=>false,'activated_at'=>time()-7200]));file_put_contents($root.'/webhook-token','test');
$bot=new Runtime($root);$learn=new ChiefLearning($bot);$checks=[];$check=function($name,$ok)use(&$checks){$checks[$name]=$ok;if(!$ok)throw new RuntimeException('TEST_FAILED_'.$name);};
$case='573001110001@s.whatsapp.net';$now=time();$e=['id'=>'ANSWER_TEST_01','chat'=>Policy::SANDRA,'at'=>$now];$data=['key'=>['fromMe'=>false],'message'=>['extendedTextMessage'=>['text'=>'Esta persona solicita un nuevo plazo de pago','contextInfo'=>['stanzaId'=>'ALERT_MID']]]];$text=Policy::text($data['message']);
$bot->query('INSERT INTO events VALUES(?,?,?,?,?,?,?,?)',[$e['id'],$e['chat'],$e['chat'],Crypt::encryptString(json_encode($data)),$now,$now,'QUEUED','']);
$bot->query('INSERT INTO tickets VALUES(?,?,?,?,?,?)',['TICKET01',$case,'CLIENT_SOURCE','Solicitud sin regla verificada','OPEN',$now-60]);
$bot->queue('TICKET01|'.Policy::SANDRA,Policy::SANDRA,'Solicitud pendiente por revisar',true);
$bot->query("UPDATE outbox SET state='READ',mid='ALERT_MID',created=?",[$now-50]);
$reply=$learn->answer($e,$data,$text,'ALERT_MID');$check('answer_recorded',str_contains($reply??'','Guardé tu respuesta'));
$ctx=$learn->context($case,$now);$check('same_case_answer_retrieved',count($ctx)===1&&$ctx[0]['event']===$e['id']&&$ctx[0]['ticket']==='TICKET01'&&$ctx[0]['answer']===$text);
$check('scope_preserved',$ctx[0]['scope']==='same-contact-case-only');
$cipher=$bot->query('SELECT body FROM chief_case_answers')->fetchColumn();$check('encrypted_at_rest',!str_contains($cipher,$text)&&Crypt::decryptString($cipher)===$text);
$check('other_contact_not_inherited',$learn->context('573001110002@s.whatsapp.net',$now)===[]);
$check('future_answer_not_inherited',$learn->context($case,$now-1)===[]);
$check('chief_not_case',$learn->context(Policy::SANDRA,$now)===[]);
$check('duplicate_not_relearned',str_contains($learn->answer($e,$data,$text,'ALERT_MID')??'','Ya tengo'));
$check('one_record',(int)$bot->query('SELECT COUNT(*) FROM chief_case_answers')->fetchColumn()===1);
$check('wrong_sender_rejected',$learn->answer(array_replace($e,['chat'=>$case]),$data,$text,'ALERT_MID')===null);
$forward=$data;$forward['message']['extendedTextMessage']['contextInfo']['isForwarded']=true;$check('forward_rejected',$learn->answer($e,$forward,$text,'ALERT_MID')===null);
$out=$data;$out['key']['fromMe']=true;$check('outbound_rejected',$learn->answer($e,$out,$text,'ALERT_MID')===null);
$check('unknown_quote_rejected',$learn->answer($e,$data,$text,'NO_MID')===null);
$check('question_not_answer',$learn->answer($e,$data,'¿Qué quiere esta persona?','ALERT_MID')===null);
$check('new_action_not_answer',$learn->answer($e,$data,'Envía estos datos al grupo','ALERT_MID')===null);
$check('bare_yes_not_answer',$learn->answer($e,$data,'Sí','ALERT_MID')===null);
$bot->query("UPDATE outbox SET state='UNCERTAIN'");$check('uncertain_source_rejected',$learn->answer($e,$data,$text,'ALERT_MID')===null);
$bot->query("UPDATE outbox SET state='READ',created=?",[$now+30]);$check('future_question_rejected',$learn->answer($e,$data,$text,'ALERT_MID')===null);
$bot->query("UPDATE outbox SET created=?,internal=0",[$now-30]);$check('normal_reply_not_case_alert',$learn->answer($e,$data,$text,'ALERT_MID')===null);
$check('retains_financial_review',str_contains(ChiefLearning::instructions(),'no políticas aprobadas')&&str_contains(ChiefLearning::instructions(),'payment_terms'));
$check('no_case_write_or_release',(int)$bot->query("SELECT COUNT(*) FROM tickets WHERE state='OPEN'")->fetchColumn()===1&&(int)$bot->query('SELECT COUNT(*) FROM chats')->fetchColumn()===0);
$check('no_messages_queued',(int)$bot->query('SELECT COUNT(*) FROM outbox')->fetchColumn()===1);
echo json_encode(['passed'=>count($checks),'failed'=>0,'tests'=>$checks,'externalMessages'=>0,'businessWrites'=>0],JSON_UNESCAPED_UNICODE).PHP_EOL;
