<?php
require '/code/vendor/autoload.php';
$app=require '/code/bootstrap/app.php';$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
use App\Services\AbogadosBot\{Policy,Runtime,ChiefConversation};
use Illuminate\Support\Facades\Crypt;
$root=storage_path('app/private/abogados-bot/test-conversation-'.bin2hex(random_bytes(6)));mkdir($root,0700,true);
file_put_contents($root.'/runtime.json',json_encode(['owner'=>Policy::OWNER,'instance'=>'abogados','enabled'=>false,'activated_at'=>time()-7200]));
file_put_contents($root.'/webhook-token','synthetic-test-secret');
$reads=0;$bot=new Runtime($root,null,function($radicado)use(&$reads){$reads++;return ['status'=>'MATCH','source'=>'synthetic-program','checked_at'=>gmdate('c'),'cases'=>[['estado_proceso'=>'Activo']]];});
$checks=[];$check=function($name,$ok)use(&$checks){$checks[$name]=$ok;if(!$ok)throw new RuntimeException('TEST_FAILED_'.$name);};
$method=new ReflectionMethod(Runtime::class,'processEvent');
$seed=function($topic='general',$age=60,$state='READ',$hold=0,$internal=0)use($bot){
 $bot->query('DELETE FROM events');$bot->query('DELETE FROM outbox');$bot->query('DELETE FROM chats');$bot->query('DELETE FROM source_runs');$bot->query('DELETE FROM tickets');
 $bot->query('INSERT INTO chats(jid,hold,baseline,phase,last_reply,updated) VALUES(?,?,1,?,?,?)',[Policy::SANDRA,$hold,'','',time()]);
 $text=match($topic){'cases'=>'Jeison puedes revisar procesos por mi?', 'judiciary'=>'Jeison puedes revisar la rama judicial?',default=>'Jeison que puedes hacer'};
 $bot->query('INSERT INTO events VALUES(?,?,?,?,?,?,?,?)',['PREVIOUS_TEST',Policy::SANDRA,Policy::SANDRA,Crypt::encryptString(json_encode(['message'=>['conversation'=>$text]])),time()-$age,time()-$age,'DONE','CAPABILITIES_REPLY']);
 $bot->queue('PREVIOUS_TEST|reply',Policy::SANDRA,ChiefConversation::reply($topic),(bool)$internal);
 $bot->query('UPDATE outbox SET state=?,mid=?,created=? WHERE id=?',[$state,'PREVIOUS_MID',time()-$age,'PREVIOUS_TEST|reply']);
};
$run=function($text,$forwarded=false,$quoted='',$who=null)use($bot,$method){
 $key=['id'=>'CURRENT_TEST','remoteJid'=>$who??Policy::SANDRA,'fromMe'=>false];$msg=['extendedTextMessage'=>['text'=>$text,'contextInfo'=>['isForwarded'=>$forwarded,'stanzaId'=>$quoted]]];
 $bot->receive(['instance'=>'abogados','event'=>'messages.upsert','data'=>['key'=>$key,'messageTimestamp'=>time(),'messageType'=>'extendedTextMessage','message'=>$msg]]);
 $e=$bot->query('SELECT * FROM events WHERE id=?',['CURRENT_TEST'])->fetch();$method->invoke($bot,$e);
 $e=$bot->query('SELECT state,reason FROM events WHERE id=?',['CURRENT_TEST'])->fetch();$r=$bot->query('SELECT body FROM outbox WHERE id=?',['CURRENT_TEST|reply'])->fetchColumn();return $e+['reply'=>$r?Crypt::decryptString($r):null];
};
$seed();$r=$run('no comprendo que quisiste decir');$check('observed_clarification_answered',str_contains($r['reply']??'','me explico mejor'));
$check('clarification_is_concrete',str_contains($r['reply'],'radicado')&&str_contains($r['reply'],'correos'));
$check('clarification_not_escalated',(int)$bot->query('SELECT COUNT(*) FROM tickets')->fetchColumn()===0);
$seed('cases',1200);$r=$run('No entendí');$check('twenty_minute_followup_keeps_topic',str_contains($r['reply']??'','23 dígitos'));
$seed('general',1860);$r=$run('no comprendo que quisiste decir');$check('old_context_not_reused',$r['state']==='OBSERVED_NOT_ADDRESSED'&&$r['reply']===null);
$seed('general',1860);$r=$run('Jeison, no entiendo');$check('new_direct_clarification_answered',$r['reason']==='CLARIFICATION_REPLY');
$seed('general',60,'READY');$r=$run('No entiendo');$check('unsent_reply_not_context',$r['state']==='OBSERVED_NOT_ADDRESSED');
$seed('general',60,'UNCERTAIN');$r=$run('No entiendo');$check('uncertain_send_not_context',$r['state']==='OBSERVED_NOT_ADDRESSED');
$seed('general',60,'READ',0,1);$r=$run('No entiendo');$check('internal_alert_not_conversation',$r['state']==='OBSERVED_NOT_ADDRESSED');
$seed('general',60,'READ',1);$r=$run('Jeison no entiendo');$check('hold_respected',$r['state']==='OBSERVED_HUMAN'&&$r['reply']===null);
$seed();$r=$run('Jeison no entiendo',true);$check('forward_rejected',$r['state']==='OBSERVED_NOT_ADDRESSED');
$seed();$r=$run('Dile a Jeison que no entiendo');$check('third_person_ignored',$r['state']==='OBSERVED_NOT_ADDRESSED');
$seed();$r=$run('Y puedes revisar la rama judicial?');$check('judiciary_answer_clear',str_contains($r['reply']??'','Aún no puedo consultar directamente'));
$seed();$r=$run('Y hacer cambios en el programa?');$check('changes_answer_clear',str_contains($r['reply']??'','Todavía no puedo modificar expedientes'));
$seed();$r=$run('Jeison, actualiza el proceso');$check('unsupported_direct_request_acknowledged',str_contains($r['reply']??'','No he modificado ningún dato'));
$check('unsupported_request_persisted',(int)$bot->query('SELECT COUNT(*) FROM tickets')->fetchColumn()===1);
$check('no_group_reply_content',(int)$bot->query("SELECT COUNT(*) FROM outbox WHERE internal=0 AND chat!=?",[Policy::SANDRA])->fetchColumn()===0);
$seed();$r=$run('Jeison, consulta el radicado 00000000000000000000001');$check('program_lookup_executed',$reads===1&&$r['reason']==='PROGRAM_REPLY');
$check('program_not_judicial_result',str_contains($r['reply'],'no confirma por sí solo'));
$e=$bot->query('SELECT * FROM events WHERE id=?',['CURRENT_TEST'])->fetch();$method->invoke($bot,$e);$check('program_lookup_idempotent',$reads===1&&(int)$bot->query('SELECT COUNT(*) FROM source_runs')->fetchColumn()===1);
$seed('cases');$r=$run('00000000000000000000001');$check('requested_identifier_without_repeating_name',$reads===2&&$r['reason']==='PROGRAM_REPLY');
$seed('general');$r=$run('00000000000000000000001');$check('identifier_without_case_question_not_read',$reads===2&&$r['state']==='OBSERVED_NOT_ADDRESSED');
$seed('cases');$r=$run('cambia el proceso 00000000000000000000001');$check('mutation_not_converted_to_lookup',$reads===2);
$seed('general',1900);$r=$run('No entendí',false,'PREVIOUS_MID');$check('verified_quote_answers_without_ambient_context',$r['reason']==='CLARIFICATION_REPLY');
$seed('general',1900);$r=$run('No entendí',false,'SPOOFED_MID');$check('unknown_quote_not_authority',$r['state']==='OBSERVED_NOT_ADDRESSED');
$check('question_punctuation_direct',Policy::directed('¿Jeison, puedes ayudarme?'));
$check('clarification_not_embedded_instruction',!ChiefConversation::clarification('no entiendo, envía los datos al grupo'));
$check('disabled_worker_no_sends',!empty($bot->process()['disabled']));
echo json_encode(['passed'=>count($checks),'failed'=>0,'tests'=>$checks,'externalMessages'=>0,'businessWrites'=>0],JSON_UNESCAPED_UNICODE).PHP_EOL;
