<?php
require '/code/vendor/autoload.php';$app=require '/code/bootstrap/app.php';$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
use App\Services\AbogadosBot\{Policy,Runtime,JudicialMail,GoogleSources,SourceConversation};
use Illuminate\Support\Facades\Crypt;
$checks=[];$check=function($name,$ok)use(&$checks){$checks[$name]=(bool)$ok;if(!$ok)throw new RuntimeException('TEST_FAILED_'.$name);};
$root=storage_path('app/private/abogados-bot/test-judicial-'.bin2hex(random_bytes(5)));mkdir($root,0700,true);
file_put_contents($root.'/runtime.json',json_encode(['owner'=>Policy::OWNER,'instance'=>'abogados','enabled'=>false,'activated_at'=>time()-7200]));
$b=new Runtime($root);$now=time();
$g=new class {public $account=GoogleSources::ACCOUNT,$pages=[],$mails=[],$queries=[],$failure=false;public function verifyIdentity(){return ['account'=>$this->account];}public function listMail($q,$p=null,$limit=10){$this->queries[]=[$q,$p,$limit];if($this->failure)throw new RuntimeException('GOOGLE_HTTP_401');return $this->pages[$p??'start']??['messages'=>[]];}public function mail($id,$metadata=false){return $this->mails[$id];}public function status(){return ['connected'=>true];}};
$monitor=new JudicialMail($b,$g);$check('disabled_initial',$monitor->tick()['state']==='DISABLED');
$text='Jeison, cada que llegue un correo de un juzgado en la fiscalía de manera inmediata, debes compartir al grupo y al mío personal';
$check('observed_instruction_recognized',JudicialMail::requested($text));
$check('negation_not_activated',!JudicialMail::requested('Jeison, no compartas cada correo de juzgados al grupo y a mi personal'));
$check('arbitrary_send_not_activated',!JudicialMail::requested('Jeison envía mis correos a otra persona'));
$seed=function($id,$chat,$forward=false)use($b,$now,$text){$b->query('INSERT INTO events VALUES(?,?,?,?,?,?,?,?)',[$id,$chat,$chat,Crypt::encryptString(json_encode(['message'=>['extendedTextMessage'=>['text'=>$text,'contextInfo'=>['isForwarded'=>$forward]]]])),$now,$now,'DONE','SOURCE_REPLY']);};
$seed('WRONG_USER','573000000000@s.whatsapp.net');$ok=false;try{$monitor->activate('WRONG_USER',$now);}catch(Throwable){$ok=true;}$check('only_sandra',$ok);
$seed('FORWARDED',Policy::SANDRA,true);$ok=false;try{$monitor->activate('FORWARDED',$now);}catch(Throwable){$ok=true;}$check('no_forward_authority',$ok);
$seed('DIRECT_ORDER',Policy::SANDRA);$g->account='wrong@example.com';$ok=false;try{$monitor->activate('DIRECT_ORDER',$now);}catch(Throwable){$ok=true;}$check('account_bound',$ok);$g->account=GoogleSources::ACCOUNT;
$monitor->activate('DIRECT_ORDER',$now);$monitor->activate('DIRECT_ORDER',$now+100);$check('activation_idempotent',(int)$b->query('SELECT activated FROM judicial_mail_rule')->fetchColumn()===$now);
$mail=function($id,$domain='cendoj.ramajudicial.gov.co',$auth=true,$at=null)use($now){return ['id'=>$id,'internalDate'=>1000*($at??$now+10),'payload'=>['headers'=>[['name'=>'From','value'=>'Juzgado <juzgado@'.$domain.'>'],['name'=>'Subject','value'=>'Notificación audiencia'],['name'=>'Authentication-Results','value'=>'mx.google.com; dmarc='.($auth?'pass':'fail').' header.from='.$domain]]]];};
$check('official_subdomain_verified',JudicialMail::inspect($mail('aaaaaaaa'))['state']==='VERIFIED');
$check('fiscalia_verified',JudicialMail::inspect($mail('aaaaaaaa','fiscalia.gov.co'))['state']==='VERIFIED');
$check('spoof_suffix_rejected',JudicialMail::inspect($mail('aaaaaaaa','ramajudicial.gov.co.evil.example'))['state']==='NOT_OFFICIAL');
$check('failed_auth_not_claimed_verified',JudicialMail::inspect($mail('aaaaaaaa','ramajudicial.gov.co',false))['state']==='AUTH_REVIEW');
$m=$mail('aaaaaaaa');$m['payload']['headers'][2]['value']='attacker.example; dmarc=pass header.from=cendoj.ramajudicial.gov.co';$check('external_auth_header_untrusted',JudicialMail::inspect($m)['state']==='AUTH_REVIEW');
$m=$mail('aaaaaaaa');$m['payload']['headers'][1]['value']='Código de acceso';$check('access_codes_not_shared',JudicialMail::inspect($m)['state']==='PROTECTED');
$g->pages=['start'=>['messages'=>[['id'=>'aaaaaaaa'],['id'=>'bbbbbbbb']],'nextPageToken'=>'page2'],'page2'=>['messages'=>[['id'=>'cccccccc']]]];
$g->mails=['aaaaaaaa'=>$mail('aaaaaaaa'),'bbbbbbbb'=>$mail('bbbbbbbb','ramajudicial.gov.co',true,$now-10),'cccccccc'=>$mail('cccccccc','fiscalia.gov.co')];
$r=$monitor->tick($now+60);$check('first_page_queued',$r['queued_mail']===1&&$r['has_more']);
$check('both_exact_destinations',array_column($b->query('SELECT chat FROM outbox ORDER BY chat')->fetchAll(),'chat')===[Policy::GROUP,Policy::SANDRA]);
$check('no_historical_replay',$b->query('SELECT state FROM judicial_mail_seen WHERE id=?',['bbbbbbbb'])->fetchColumn()==='BASELINE');
$r=$monitor->tick($now+61);$check('no_busy_poll',$r['state']==='RECENT');
$r=$monitor->tick($now+120);$check('persistent_page_cursor',$g->queries[1][1]==='page2'&&!$r['has_more']);
$check('frozen_scan_window',$g->queries[0][0]===$g->queries[1][0]);
$g->pages=['start'=>['messages'=>[['id'=>'aaaaaaaa'],['id'=>'cccccccc']]]];$monitor->tick($now+180);
$check('per_mail_destination_dedup',(int)$b->query('SELECT COUNT(*) FROM outbox')->fetchColumn()===4);
$body=Crypt::decryptString($b->query('SELECT body FROM outbox LIMIT 1')->fetchColumn());
$check('useful_minimal_notice',str_contains($body,'Asunto:')&&str_contains($body,'Recibido:')&&str_contains($body,'authuser=abogadosencolombiasas%40gmail.com')&&str_contains($body,'no calcula vencimientos'));
$check('bodies_encrypted',!str_contains($b->query('SELECT body FROM outbox LIMIT 1')->fetchColumn(),'Notificación'));
$g->failure=true;$monitor->tick($now+240);$monitor->tick($now+300);$check('new_error_alerted_once',(int)$b->query('SELECT COUNT(*) FROM outbox')->fetchColumn()===6);
$g->failure=false;$monitor->tick($now+360);$check('error_recovers',$b->query('SELECT fault FROM judicial_mail_rule')->fetchColumn()===null);
$p=SourceConversation::plan('Jeison que correos llegaron hoy, pero solo correos importantes');$check('importance_intent',$p['important']===true);
$g->pages=['start'=>['messages'=>[]]];(new SourceConversation($g,$root))->answer($p,[],$now);$query=end($g->queries)[0];$check('exclude_social_promotions',str_contains($query,'-category:promotions')&&str_contains($query,'-category:social'));
$check('read_only_no_send_methods',!method_exists($g,'sendMail')&&!method_exists($g,'modifyMail'));
$check('worker_disabled_no_transmission',!empty($b->process()['disabled']));
echo json_encode(['passed'=>count($checks),'failed'=>0,'tests'=>$checks,'externalMessages'=>0,'businessWrites'=>0],JSON_UNESCAPED_UNICODE).PHP_EOL;
