<?php
require '/code/vendor/autoload.php';$app=require '/code/bootstrap/app.php';$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
use App\Services\AbogadosBot\{Runtime,Policy,ChiefOperations,JudicialMail,GoogleSources};use Illuminate\Support\Facades\Crypt;
$checks=[];$check=function($n,$ok)use(&$checks){$checks[$n]=(bool)$ok;if(!$ok)throw new RuntimeException('TEST_FAILED_'.$n);};
$root=storage_path('app/private/abogados-bot/test-notice-'.bin2hex(random_bytes(5)));mkdir($root,0700,true);file_put_contents($root.'/runtime.json',json_encode(['owner'=>Policy::OWNER,'instance'=>'abogados','enabled'=>false,'activated_at'=>time()-9000]));$b=new Runtime($root);
$text='Jeison, revisa quirúrgicamente, pero mándame sólo mensajes muy cortos como notificándome que es de un juzgado, pero mensajes es muy corto, no tan largos';
$check('actual_source_recognized',ChiefOperations::kind($text)==='brief_notifications');
$check('quoted_policy_not_authority',ChiefOperations::kind('Ella dijo: '.$text)===null);
$check('other_recipient_not_permitted',ChiefOperations::kind('Jeison, envíame mensajes cortos de correos a otro grupo')===null);
$check('ordinary_search_unchanged',ChiefOperations::kind('Jeison revisa los correos de hoy')===null);
$ops=new ChiefOperations($b);$e=['id'=>'NOTICE_DIRECT_TEST','chat'=>Policy::SANDRA,'at'=>time()];$reply=$ops->handle($e,$text,'brief_notifications');$ops->handle($e,$text,'brief_notifications');
$check('short_ack_without_question',mb_strlen($reply)<130&&!str_contains($reply,'?'));
$check('rule_with_exact_source',$b->query('SELECT source FROM chief_operational_rules WHERE kind=?',['brief_notifications'])->fetchColumn()===$e['id']);
$check('one_request',(int)$b->query('SELECT COUNT(*) FROM chief_operational_requests')->fetchColumn()===1);
$r=json_decode(Crypt::decryptString($b->query('SELECT body FROM chief_operational_rules')->fetchColumn()),true);$check('scope_not_legal',$r['scope']==='administrative_notifications_only'&&$r['sourceText']===$text);
$wrong=$e;$wrong['chat']='573000000000@s.whatsapp.net';try{$ops->handle($wrong,$text,'brief_notifications');$rejected=false;}catch(Throwable){$rejected=true;}$check('identity_required',$rejected);
$phone='573000001830@s.whatsapp.net';$b->query('INSERT INTO chats VALUES(?,0,1,?,?,?)',[$phone,'','',time()]);
$ticket=$b->ticket(['id'=>'UNREAD_ATTACHMENT_TEST','chat'=>$phone],'Archivo recibido: revisión de contenido');
$check('unread_media_no_alert',(int)$b->query('SELECT COUNT(*) FROM outbox')->fetchColumn()===0);
$check('unread_media_preserved',$b->query('SELECT state FROM tickets WHERE id=?',[$ticket])->fetchColumn()==='CONTENT_UNREVIEWED');
$b->query('UPDATE chats SET hold=1 WHERE jid=?',[$phone]);$b->ticket(['id'=>'ALREADY_STAFF_TEST','chat'=>$phone],'Consulta jurídica: revisión profesional');
$check('already_staff_no_alert',(int)$b->query('SELECT COUNT(*) FROM outbox')->fetchColumn()===0);
$check('not_claimed_legally_resolved',$b->query('SELECT state FROM tickets WHERE event=?',['ALREADY_STAFF_TEST'])->fetchColumn()==='IN_HUMAN_REVIEW');
$b->query('UPDATE chats SET hold=0 WHERE jid=?',[$phone]);$later=$b->ticket(['id'=>'LATER_STAFF_TEST','chat'=>$phone],'Queja: revisión');$check('new_actionable_two_destinations',(int)$b->query('SELECT COUNT(*) FROM outbox')->fetchColumn()===2);
$b->query('UPDATE chats SET hold=1 WHERE jid=?',[$phone]);
// A pre-release unread-file notice still READY must not escape the new guard.
$b->query("UPDATE tickets SET state='OPEN' WHERE id=?",[$ticket]);foreach([Policy::SANDRA,Policy::GROUP] as $dest)$b->queue($ticket.'|'.$dest,$dest,'Old unread-file alert',true);
file_put_contents($root.'/runtime.json',json_encode(['owner'=>Policy::OWNER,'instance'=>'abogados','enabled'=>true]));$active=new Runtime($root);$active->flush();
$check('staff_before_send_suppresses_both',(int)$b->query("SELECT COUNT(*) FROM outbox WHERE state='SUPPRESSED_HUMAN' AND id LIKE ?",[$later.'|%'])->fetchColumn()===2);
$check('pre_release_unread_not_sent',(int)$b->query("SELECT COUNT(*) FROM outbox WHERE state='SUPPRESSED_HUMAN' AND id LIKE ?",[$ticket.'|%'])->fetchColumn()===2);
$mail=['id'=>'aaaaaaaa','threadId'=>'bbbbbbbb','internalDate'=>100000,'payload'=>['headers'=>[['name'=>'From','value'=>'Juzgado <juzgado@cendoj.ramajudicial.gov.co>'],['name'=>'Subject','value'=>'Notificación audiencia'],['name'=>'Message-ID','value'=>'<original@court.test>'],['name'=>'Authentication-Results','value'=>'mx.google.com; dmarc=pass header.from=cendoj.ramajudicial.gov.co']]]];
$token=$mail;$token['payload']['headers'][1]['value']='Token: PRIVATE de acceso';$check('token_does_not_notify',JudicialMail::inspect($token)['state']==='PROTECTED');
$auto=$mail;$auto['payload']['headers'][1]['value']='Respuesta automática: memorial';$auto['payload']['headers'][]=['name'=>'Auto-Submitted','value'=>'auto-replied'];$check('verified_automatic_receipt_quiet',JudicialMail::inspect($auto)['state']==='INFORMATIONAL_RECEIPT');
array_pop($auto['payload']['headers']);$check('subject_alone_not_hidden',JudicialMail::inspect($auto)['state']==='VERIFIED');
$thread=['id'=>'bbbbbbbb','messages'=>[['internalDate'=>110000,'labelIds'=>['SENT'],'payload'=>['headers'=>[['name'=>'From','value'=>GoogleSources::ACCOUNT],['name'=>'In-Reply-To','value'=>'<original@court.test>']]]]]];
$check('exact_sent_reply_recognized',JudicialMail::answered($mail,$thread));
$t=$thread;$t['messages'][0]['internalDate']=90000;$check('previous_sent_not_answer',!JudicialMail::answered($mail,$t));
$t=$thread;$t['messages'][0]['labelIds']=[];$check('incoming_not_answer',!JudicialMail::answered($mail,$t));
$t=$thread;$t['messages'][0]['payload']['headers'][1]['value']='<unrelated@court.test>';$check('same_thread_not_enough',!JudicialMail::answered($mail,$t));
$t=$thread;$t['messages'][0]['payload']['headers'][0]['value']='outsider@example.com';$check('other_sender_not_authority',!JudicialMail::answered($mail,$t));
$t=$thread;$t['id']='cccccccc';$check('wrong_thread_rejected',!JudicialMail::answered($mail,$t));
$notice=JudicialMail::message(JudicialMail::inspect($mail),'aaaaaaaa');$check('brief_no_implied_task',!str_contains($notice,'Revisen')&&!str_contains($notice,'pendiente')&&mb_strlen($notice)<350);
$g=new class {public array $mails=[],$threads=[];public int $threadCalls=0;public function verifyIdentity(){return ['account'=>GoogleSources::ACCOUNT];}public function listMail($q,$p=null,$limit=10){return ['messages'=>array_map(fn($id)=>['id'=>$id],array_keys($this->mails))];}public function mail($id,$metadata=false){if(!$metadata)throw new RuntimeException('BODY_NOT_NEEDED');return $this->mails[$id];}public function mailThreadMetadata($id){$this->threadCalls++;return $this->threads[$id]??['id'=>$id,'messages'=>[]];}};
$mail['internalDate']=time()*1000;$token['internalDate']=$mail['internalDate'];$auto['internalDate']=$mail['internalDate'];$auto['payload']['headers'][]=['name'=>'Auto-Submitted','value'=>'auto-generated'];$thread['messages'][0]['internalDate']=$mail['internalDate']+1;
$g->mails=['aaaaaaaa'=>$mail,'cccccccc'=>$token,'dddddddd'=>$auto,'eeeeeeee'=>array_replace($mail,['threadId'=>'ffffffff'])];$g->threads=['bbbbbbbb'=>$thread];
$monitor=new JudicialMail($b,$g);$b->query('INSERT INTO judicial_mail_rule(id,enabled,activated,watermark) VALUES(1,1,?,?)',[time()-60,time()-60]);$r=$monitor->tick(time()+1);
$check('only_unanswered_new_mail_queued',$r['queued_mail']===1&&(int)$b->query("SELECT COUNT(*) FROM outbox WHERE state='READY'")->fetchColumn()===2);
$check('answered_recorded_not_deleted',$b->query('SELECT state FROM judicial_mail_seen WHERE id=?',['aaaaaaaa'])->fetchColumn()==='REPLIED_IN_THREAD');
$check('automatic_recorded_quiet',$b->query('SELECT state FROM judicial_mail_seen WHERE id=?',['dddddddd'])->fetchColumn()==='INFORMATIONAL_RECEIPT');
$check('token_recorded_quiet',$b->query('SELECT state FROM judicial_mail_seen WHERE id=?',['cccccccc'])->fetchColumn()==='PROTECTED');
$check('thread_check_only_for_real_new_messages',$g->threadCalls===2);
$monitor->tick(time()+70);$check('repeat_scan_no_resend',(int)$b->query("SELECT COUNT(*) FROM outbox WHERE state='READY'")->fetchColumn()===2);
echo json_encode(['passed'=>count($checks),'failed'=>0,'tests'=>$checks,'externalMessages'=>0,'businessWrites'=>0]).PHP_EOL;
