<?php
require '/code/vendor/autoload.php';
$app=require '/code/bootstrap/app.php';$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
use App\Services\AbogadosBot\{Policy,Runtime};
use Illuminate\Support\Facades\Crypt;
$checks=[];$check=function($name,$ok)use(&$checks){$checks[$name]=$ok;if(!$ok)throw new RuntimeException('TEST_FAILED_'.$name);};
$text='Soy codeudor de una persona y ayer nos llegó una carta de embargo. Quisiera saber el horario de atención de la oficina para llegar a un acuerdo de pago';
$plan=Policy::plan('payment_terms','purpose',false,[],$text);
$check('observed_request_answers_office_hours',str_contains($plan['reply'],'horario de atención de la oficina'));
$check('no_schedule_fabricated',str_contains($plan['reply'],'Aún no tengo confirmado')&&!preg_match('/\d/',$plan['reply']));
$check('no_agreement_announced',!str_contains($plan['reply'],'acuerdo')&&!str_contains($plan['reply'],'condiciones'));
$check('review_remains',$plan['phase']==='review'&&$plan['ticket']==='Horario de oficina: confirmar información vigente');
$check('office_question_matches',Policy::plan('appointment','purpose',true,[],'¿Cuál es el horario de atención de la oficina?')['phase']==='review');
$check('warm_greeting_once',substr_count(Policy::plan('appointment','purpose',true,[],'¿Cuál es el horario de atención de la oficina?')['reply'],'¡Hola!')===1);
$check('negated_question_not_matched',Policy::plan('payment_terms','purpose',false,[],'No quiero saber el horario de atención de la oficina; necesito un plazo.')['ticket']!=='Horario de oficina: confirmar información vigente');
$check('court_hours_not_office_rule',Policy::plan('payment_terms','purpose',false,[],'Quisiera saber el horario de atención del juzgado.')['ticket']!=='Horario de oficina: confirmar información vigente');
$check('statement_not_question',Policy::plan('payment_terms','purpose',false,[],'El horario de atención de la oficina es de 2 a 4.')['ticket']!=='Horario de oficina: confirmar información vigente');
foreach(['legal','complaint','third_party','stop'] as $intent){$check('retain_'.$intent,Policy::plan($intent,'purpose',false,[],$text)===Policy::plan($intent,'purpose',false));}
$check('payment_stays_verification',Policy::plan('payment','purpose',false,[],$text)['ticket']==='Pago o acuerdo: requiere verificación y autorización');
$check('regular_agreement_stays_review',Policy::plan('payment_terms','purpose',false,[],'Quiero que acepten mi acuerdo por cuotas.')===Policy::plan('payment_terms','purpose',false));
$root=storage_path('app/private/abogados-bot/test-office-hours-'.bin2hex(random_bytes(6)));mkdir($root,0700,true);
file_put_contents($root.'/runtime.json',json_encode(['owner'=>Policy::OWNER,'instance'=>'abogados','enabled'=>false,'activated_at'=>time()-7200]));
file_put_contents($root.'/webhook-token','synthetic-test-secret');
$bot=new Runtime($root);$phone='573000000001@s.whatsapp.net';$id='SYNTHETIC_OFFICE_HOURS';
$bot->query('INSERT INTO chats(jid,hold,baseline,phase,last_reply,updated) VALUES(?,1,1,?,?,?)',[$phone,'','',time()]);
$bot->query('INSERT INTO events VALUES(?,?,?,?,?,?,?,?)',[$id,$phone,$phone,Crypt::encryptString(json_encode(['message'=>['conversation'=>$text]])),time(),time(),'QUEUED','']);
$event=$bot->query('SELECT * FROM events WHERE id=?',[$id])->fetch();
$method=new ReflectionMethod(Runtime::class,'processEvent');$method->invoke($bot,$event);
$check('human_hold_suppresses_office_reply',$bot->query('SELECT state FROM events WHERE id=?',[$id])->fetchColumn()==='OBSERVED_HUMAN'&&(int)$bot->query('SELECT COUNT(*) FROM outbox')->fetchColumn()===0);
// Separate test fixture: an unattended request is still routed to both destinations.
$bot->query('UPDATE chats SET hold=0 WHERE jid=?',[$phone]);
$ticket=$bot->ticket($event,$plan['ticket']);$bot->ticket($event,$plan['ticket']);
$outbox=$bot->query('SELECT chat,body FROM outbox ORDER BY chat')->fetchAll();
$check('one_alert_per_destination',count($outbox)===2);
$check('only_authorized_destinations',array_column($outbox,'chat')===[Policy::GROUP,Policy::SANDRA]);
$alert=Crypt::decryptString($outbox[0]['body']);
$check('alert_addresses_actual_question',str_contains($alert,'horario de atención de la oficina'));
$check('alert_minimizes_private_context',!str_contains($alert,'embargo')&&!str_contains($alert,'codeudor')&&!str_contains($alert,'573000000001'));
$check('disabled_worker_no_delivery',!empty($bot->process()['disabled']));
$bot->flush();$check('disabled_flush_keeps_alerts_local',(int)$bot->query("SELECT COUNT(*) FROM outbox WHERE state='READY'")->fetchColumn()===2);
echo json_encode(['passed'=>count($checks),'failed'=>0,'tests'=>$checks,'externalMessages'=>0,'businessWrites'=>0],JSON_UNESCAPED_UNICODE).PHP_EOL;
